import PropTypes from "prop-types";
import clsx from "clsx";
import Button from "@ui/button";

const TermsAndConditionsArea = ({ className, space }) => (
    <div
        className={clsx(
            "terms-condition-area",
            space === 1 && "rn-section-gapTop",
            className
        )}
    >
        <div className="container">
            <div className="row">
                <div className="offset-lg-2 col-lg-8 ">
                    <div className="condition-wrapper">
                        <h2>BDC TERMS &amp; CONDITIONS</h2>
                        <p>
                            Bad Dogs Company™ (BDC) is a collection of digital artwork
                            non-fungible tokens (NFTs) comprised of, among other
                            things, Bad Dogs Genesis, Bad Dogs 4k,
                            CyberDogs 3077™, Cyber City, and Bad Dogs Energy
                            Pack™ (each, a &quot;BDC NFT&quot;) running on the Ethereum network.
                            This website is only an interface allowing participants to
                            exchange digital collectibles. Users are entirely
                            responsible for the safety and management of their own
                            private Ethereum wallets and validating all transactions
                            and contracts generated by this website before approval.
                        </p>
                        <p>
                            Furthermore, as the Bad Dogs Company™ smart contract runs
                            on the Ethereum network, there is no ability to undo,
                            reverse, or restore any transactions. This website and
                            its connected services are provided “as is” and “as
                            available” without warranty of any kind. By using this
                            website you are accepting sole responsibility for any and
                            all transactions involving BDC digital collectibles.
                        </p>

                        <h2>OWNERSHIP</h2>
                        <p>
                            i. Each BDC NFT is an NFT on the Ethereum blockchain.
                            When you purchase an NFT, you own the underlying BDC NFT.
                            Ownership of the NFT is mediated entirely by the smart
                            contract and the Ethereum Network. At no point may we
                            seize, freeze, or otherwise modify the ownership of any
                            BDC NFT.
                        </p>
                        <p>
                            ii. Subject to your continued compliance with these terms,
                            Bad Dogs Company™ grants you a worldwide, royalty-free
                            license to use, copy, and display the purchased art,
                            along with any extensions that you choose to create or
                            use, solely for the following purposes:
                            <ol type="a">
                                <li>for your own personal, non-commercial use;</li>
                                <li>
                                    as part of a marketplace that permits the purchase
                                    and sale of your BDC NFT, provided that the
                                    marketplace cryptographically verifies each BDC
                                    NFT owner’s rights to display the art for their
                                    BDC NFT to ensure that only the actual owner can
                                    display the art; or
                                </li>
                                <li>
                                    as part of a third party website or application
                                    that permits the inclusion, involvement, or
                                    participation of your BDC NFT, provided that the
                                    website/application cryptographically verifies each
                                    BDC NFT owner’s rights to display the art for their
                                    BDC NFT to ensure that only the actual owner can
                                    display the art, and provided that the art is no
                                    longer visible once the owner of the BDC NFT
                                    leaves the website/application.
                                </li>
                            </ol>
                        </p>
                        <p>
                            iii. Subject to your continued compliance with these terms,
                            Bad Dogs Company™ grants you an unlimited, worldwide license
                            to use, copy, and display the purchased art for the purpose
                            of creating derivative works based upon the art
                            (“Commercial Use”). Examples of such Commercial Use would
                            be the use of the art to produce and sell merchandise
                            products (t-shirts etc.) displaying copies of the art.
                            For the sake of clarity, nothing in this paragraph will be
                            deemed to restrict you from:
                            <ol type="a">
                                <li>
                                    owning or operating a marketplace that permits the
                                    use and sale of BDC NFTs generally, provided
                                    that the marketplace cryptographically verifies
                                    each BDC NFT owner’s rights to display the art for
                                    their BDC NFT to ensure that only the actual owner
                                    can display the art;
                                </li>
                                <li>
                                    owning or operating a third party website or application
                                    that permits the inclusion, involvement, or participation
                                    of BDC NFTs generally, provided that the third party
                                    website or application cryptographically verifies each
                                    BDC NFT owner’s rights to display the art for their
                                    BDC NFT to ensure that only the actual owner can display
                                    the art, and provided that the art is no longer visible
                                    once the owner of the purchased BDC NFT leaves the
                                    website/application; or
                                </li>
                                <li>earning revenue from any of the foregoing.</li>
                            </ol>
                        </p>
                    </div>
                </div>
            </div>
            {/* <div className="row mt--50">
                <div className="offset-lg-2 col-lg-8">
                    <Button path="#" size="medium" className="mr--15">
                        Accept
                    </Button>
                    <Button path="#" color="primary-alta" size="medium">
                        Decline
                    </Button>
                </div>
            </div> */}
        </div>
    </div>
);

TermsAndConditionsArea.propTypes = {
    className: PropTypes.string,
    space: PropTypes.oneOf([1]),
};
TermsAndConditionsArea.defaultProps = {
    space: 1,
};

export default TermsAndConditionsArea;
